[package]
name = "rust-client"
version = "0.1.0"
edition = "2018"

[lib]
name="perfload"
path="/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_socketio = "0.2.4"
serde_json = "1.0.67"
systemstat = "0.1.8"
